### ISSUE TITLE
[Enhancement] Letting user know if their drawing has been saved

### ISSUE THREAD

**Issue by kasayachith** [info442-spr22/g-team#156] opened 2022-05-18 16:36 UTC
After drawing something, I clicked on the "save" button and nothing happened on that page so I was confused if it was doing anything or not (but it does work because I saw my drawing in the gallery). I think it would be helpful to show the user that their drawing has been successfully saved to show them that the system actually did something through a pop-up message of some sort.

**Comment by sharlenef** [comment] 2022-05-23 16:36
Duplicate of #134 (#139, #155, #156, #171)

**Closed by sharlenef** 2022-05-23 16:36 UTC
Labels: duplicate
