### ISSUE TITLE
Enhancement: Notify User About Saved Image

### ISSUE THREAD

**Issue by abequette99** [info442-spr22/g-team#139] opened 2022-05-18 16:11 UTC
Description: Add a message or pop up saying image was saved. When trying to save an image I had no idea if it was saved or not until I clicked on the gallery's page.

Explanation: It would be useful to have a small message saying go check out gallery to view saved image or a message saying saved because after I hit saved I was confused as to where it went or if it was saved.

**Comment by sharlenef** [comment] 2022-05-23 16:32
Duplicate of #134 (#139, #155, #156, #171)

**Closed by sharlenef** 2022-05-23 16:32 UTC
Labels: duplicate
