### ISSUE TITLE
Enhancement: show indication to user which shape was selected while drawing

### ISSUE THREAD

**Issue by xxiaouw** [info442-spr22/g-team#147] opened 2022-05-18 16:19 UTC
On the scrap book page, it would be nice if when the user selected the star shape, there would keep be an indication on the shape selection bar that the star shape is being selected. This would be helpful for the user to keep track of what they are doing and ensure them that this shape is still selected.

**Comment by fretws** [comment] 2022-05-23 17:28
Duplicate of #146

**Closed by fretws** 2022-05-23 17:28 UTC
Labels: duplicate, enhancement, verified
