### ISSUE TITLE
Enhancement: can see how the text changes as changing the font size and font style

### ISSUE THREAD

**Issue by ctang0416** [info442-spr22/g-team#172] opened 2022-05-19 05:53 UTC
When we can add text to the scrapbook, we can change the font size and font style. However, after we edit the font size and font style, we can't see how the text will change until we hit enter. After we hit enter, the text can't be changed anymore. Therefore, I think it would be better to improve the feature so that when we the font size and font style, we can see how the text changes at the same time.

**Comment by sharlenef** [comment] 2022-05-23 17:25
Duplicate of #137

**Closed by sharlenef** 2022-05-23 17:25 UTC
Labels: duplicate, enhancement
