### ISSUE TITLE
(Enhancement) Save Notification

### ISSUE THREAD

**Issue by Jaehoon01** [info442-spr22/g-team#171] opened 2022-05-19 05:49 UTC
One minor feature that I think would be nice is if it notified me that my scrapbook was saved. At first, I didn't realize it had been saved until I went to the gallery tab so I think a small message when saved is clicked would be nice! Chrome on MacOS.

**Comment by sharlenef** [comment] 2022-05-23 16:38
Duplicate of #134 (#139, #155, #156, #171)

**Closed by sharlenef** 2022-05-23 16:38 UTC
Labels: duplicate
